# Site settings
title: Piyush's Webpage
description: About me
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://piyushgoel997.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Piyush Goel
user_title: Always Learning something new
email: piyushgoel997@gmail.com
twitter_username: lorem_ipsum
github_username:  piyushgoel997
gplus_username:  piyushgoel997

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
